# Generated by Django 3.2.3 on 2021-08-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inserted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
