# Generated by Django 3.2.3 on 2021-08-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_book_inserted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
