# Generated by Django 3.2.3 on 2021-08-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210806_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='inserted_at',
        ),
    ]
